### ISSUE TITLE
Running strest-grpc on Linkerd

### ISSUE THREAD

**Issue by farquet** [BuoyantIO/strest-grpc#53]
Hello,
Running `strest-grpc` works fine if I directly connect the client to the server like this : 
```
$ ./strest-grpc client --interval=5s --address=:11111
$ ./strest-grpc server --address=:11111
```
However, if I start Linkerd and try to connect the client to it and have Linkerd proxy it to the server, I get this error : 
```
W 1009 12:06:05.290 CEST THREAD28: Exception propagated to the default monitor (upstream address: /127.0.0.1:56900, downstream address: n/a, label: 0.0.0.0/4143).
io.buoyant.router.RoutingFactory$UnknownDst: Unknown destination: Request("PRI *", from /127.0.0.1:56900) / Host header is absent
```
despite the fact that everything seems to be running on the proper ports as I see on stdout : 
```
I 1009 12:05:44.015 CEST THREAD1: serving http admin on /0.0.0.0:4191
I 1009 12:05:44.164 CEST THREAD1: serving http on /0.0.0.0:4143
starting gRPC server on :11111
```
Services have been started like this : 
```
./strest-grpc server --address=:11111
./strest-grpc client --interval=5s --address=localhost:4143
```
Linkerd with the following yaml file : 
```
admin:
    ip: 0.0.0.0
    port: 4191
routers:
    - protocol: http
      experimental: true # for older linkerds
      dtab: /svc => /$/inet/127.1/11111
      servers:
      - ip: 0.0.0.0
        port: 4143
telemetry:
    - kind: io.l5d.prometheus
```
Any clue what is going on ? Or how to debug it ?

Thanks

**Comment by siggy** [comment]
@farquet You're very close, just change `protocol` to `h2`...
```yaml
admin:
  ip: 0.0.0.0
  port: 4191
routers:
- protocol: h2
  dtab: /svc => /$/inet/127.1/11111
  servers:
  - ip: 0.0.0.0
    port: 4143
telemetry:
- kind: io.l5d.prometheus
```

For next time, best to ask questions like this in [Linkerd Discourse](https://discourse.linkerd.io/), or [Linkerd Slack](https://slack.linkerd.io/) for quicker questions. Github issues are best for bugs.
